# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.CharField(blank=True, default='', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('home_score', models.SmallIntegerField(default=0)),
                ('away_score', models.SmallIntegerField(default=0)),
                ('away_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournament.Entry')),
                ('home_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournament.Entry')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('state', models.SmallIntegerField(choices=[(0, 'Setup'), (1, 'Play'), (2, 'Complete')], default=0)),
                ('type', models.SmallIntegerField(choices=[(0, 'Round-robin'), (1, 'Pools')], default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together=set([('title', 'event_date')]),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='entry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournament.Player'),
        ),
        migrations.AddField(
            model_name='entry',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournament.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('player', 'tournament')]),
        ),
    ]
